name: PR Open Check

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  refuse:
    permissions:
      issues: write  # for actions-cool/pr-welcome to create, update & react on issues
      pull-requests: write  # for actions-cool/pr-welcome to request reviewer
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions-cool/pr-welcome@4bd317d60ef3b40a3ccda39c22f66c3358010f92
        with:
          refuse-issue-label: 🎱 Collaborate PR only
          need-creator-authority: write
          comment: |
            Hi @${{ github.event.pull_request.user.login }}. The issue mentioned in this PR needs to be confirmed with the designer or core team. Thank you for your contribution! 😊

            你好 @${{ github.event.pull_request.user.login }}。这个 PR 提及的 issue 需要和设计师或核心团队进行确认！感谢您的贡献！😊
          close: false
          reviewers: |
            MadCcc
            zombieJ

  check-changelog:
    permissions:
      pull-requests: write  # for actions-cool/pr-check-fill to create or update PR comments
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: check fill
        uses: actions-cool/pr-check-fill@18b3dfd7f633f77b28f31b0a89ec9e8996fdbf5c
        with:
          filter-start: '|'
          require-include: '🇺🇸 English, 🇨🇳 Chinese, 🇺🇸 英文, 🇨🇳 中文'
          comment-body: |
            - 🚨 @${{ github.event.pull_request.user.login }}, Please fill changelog in PR content
              > - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
              > - Describe the impact of the changes on developers, not the solution approach.
              > - Reference: https://ant.design/changelog

            - 🚨 @${{ github.event.pull_request.user.login }}, 请填写 PR 中的 changelog
              > - 郑重地阅读 [如何维护更新日志](https://keepachangelog.com/zh-CN/1.1.0/)
              > - 描述改动对开发者有哪些影响，而非解决方式
              > - 可参考：https://ant.design/changelog-cn

            ![](https://github.com/ant-design/ant-design/assets/507615/14c767db-e40f-42a1-9aab-553037eb1ab6)
          skip-title-start: 'docs, chore, test, ci'
