name: 📦 Size Limit

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  issues: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  size:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: utooland/setup-utoo@e63ce40ce5f7e9838c666a57479344e91c3a9795 # v1
      - name: size-limit
        uses: ant-design/size-limit-action@1cd308b2fb976363849b02434e706bbca8727aa1 # master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: ut
          build_script: dist
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          PRODUCTION_ONLY: 1
          CI_JOB_NUMBER: 1
