name: Verify Package Version

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  verify:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: write  # for actions-cool/verify-package-version to comment on PR
    runs-on: blacksmith-4vcpu-ubuntu-2404
    if: contains(github.event.pull_request.title, 'changelog') || contains(github.event.pull_request.title, 'release')
    steps:
      - uses: actions/checkout@v6
      - name: verify-version
        uses: actions-cool/verify-package-version@1598c3d315f361b21ab44f304c26642d7f55d17a # v1
        with:
          title-include-content: docs
          title-include-version: true
          open-comment: true
